### ISSUE TITLE
Node complaining about Syntax.

### ISSUE THREAD

**Issue by mick-duffin** [duncanthrax/iptv-m3u-restream#1]
Hi,

I am getting the below when I try to run the re-streamer (its probably something I am doing wrong though).

mick@ubuntu:~/restream/iptv-m3u-restream$ node restream.js
/home/mick/restream/iptv-m3u-restream/restream.js:8
const { spawn } = require('child_process');
      ^

SyntaxError: Unexpected token {

Node ver 12.13.0

**Comment by duncanthrax** [comment]
This is odd - the destructuring syntax has been in node for a long time. Are you sure you are running 12.13.0? Maybe you have several versions installed, and the one on the path is older? Just run "node -v" to check. Other than that, I have no idea why that happens.

**Comment by mick-duffin** [comment]
> This is odd - the destructuring syntax has been in node for a long time. Are you sure you are running 12.13.0? Maybe you have several versions installed, and the one on the path is older? Just run "node -v" to check. Other than that, I have no idea why that happens.

Hi, I had multiple Node installs, removed all but the latest stable and I have now moved on! Thanks for your help. Mike
